# Generated by Django 3.2.4 on 2021-07-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='categories.categories'),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('slug', 'parent')},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
    ]
