# Generated by Django 3.2.4 on 2021-07-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDName', models.CharField(max_length=100, verbose_name='Product Name ')),
                ('PRDDesc', models.TextField(verbose_name='Description')),
                ('PRDImage', models.ImageField(blank=True, null=True, upload_to='prodcut/', verbose_name='Image')),
                ('PRDPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('PRDDiscountPrice', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Price')),
                ('PRDCost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cost')),
                ('PRDCreated', models.DateTimeField(verbose_name='Created At')),
                ('PRDSLug', models.SlugField(blank=True, null=True, verbose_name='Product URL')),
                ('PRDISNew', models.BooleanField(default=True, verbose_name='New Product ')),
                ('PRDISBestSeller', models.BooleanField(default=False, verbose_name='Best Seller')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDIImage', models.ImageField(upload_to='prodcut/', verbose_name='Image')),
                ('PRDIProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='Product')),
            ],
        ),
    ]
